// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using ProyTelesecundaria;

#nullable disable

namespace ProyTelesecundaria.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20241120171316_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("ProyTelesecundaria.Models.AlumnoMateria", b =>
                {
                    b.Property<int>("Matricula")
                        .HasColumnType("int");

                    b.Property<int>("IDMateria")
                        .HasColumnType("int");

                    b.Property<string>("PeriodoBimestre")
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<int>("Calificacion")
                        .HasColumnType("int");

                    b.HasKey("Matricula", "IDMateria", "PeriodoBimestre");

                    b.HasIndex("IDMateria");

                    b.ToTable("AlumnoMateria", (string)null);
                });

            modelBuilder.Entity("ProyTelesecundaria.Models.Alumnos", b =>
                {
                    b.Property<int>("Matricula")
                        .HasColumnType("int");

                    b.Property<string>("Apellido")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("Correo")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("CorreoTutor")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("Direccion")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<DateTime>("FechaNacimiento")
                        .HasColumnType("datetime2");

                    b.Property<int>("Grado")
                        .HasColumnType("int");

                    b.Property<string>("Grupo")
                        .IsRequired()
                        .HasMaxLength(1)
                        .HasColumnType("nvarchar(1)");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("NombreTutor")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("Telefono")
                        .IsRequired()
                        .HasMaxLength(15)
                        .HasColumnType("nvarchar(15)");

                    b.Property<string>("TelefonoTutor")
                        .IsRequired()
                        .HasMaxLength(15)
                        .HasColumnType("nvarchar(15)");

                    b.HasKey("Matricula");

                    b.ToTable("Alumnos", (string)null);
                });

            modelBuilder.Entity("ProyTelesecundaria.Models.Aula", b =>
                {
                    b.Property<int>("IDAula")
                        .HasColumnType("int");

                    b.Property<int>("Capacidad")
                        .HasColumnType("int");

                    b.HasKey("IDAula");

                    b.ToTable("Aulas", (string)null);
                });

            modelBuilder.Entity("ProyTelesecundaria.Models.MaestroMateria", b =>
                {
                    b.Property<int>("IDMaestro")
                        .HasColumnType("int");

                    b.Property<int>("IDMateria")
                        .HasColumnType("int");

                    b.HasKey("IDMaestro", "IDMateria");

                    b.HasIndex("IDMateria");

                    b.ToTable("MaestroMateria", (string)null);
                });

            modelBuilder.Entity("ProyTelesecundaria.Models.Maestros", b =>
                {
                    b.Property<int>("IdMaestro")
                        .HasColumnType("int");

                    b.Property<string>("Apellidos")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("Correo")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("Horario")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<int>("IdAula")
                        .HasColumnType("int");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("Telefono")
                        .IsRequired()
                        .HasMaxLength(15)
                        .HasColumnType("nvarchar(15)");

                    b.HasKey("IdMaestro");

                    b.HasIndex("IdAula");

                    b.ToTable("Maestros", (string)null);
                });

            modelBuilder.Entity("ProyTelesecundaria.Models.Materia", b =>
                {
                    b.Property<int>("IDMateria")
                        .HasColumnType("int");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("IDMateria");

                    b.ToTable("Materias", (string)null);
                });

            modelBuilder.Entity("ProyTelesecundaria.Models.Usuario", b =>
                {
                    b.Property<int>("IDUsuario")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IDUsuario"));

                    b.Property<string>("Contraseña")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Correo")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("TipoUsuario")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("IDUsuario");

                    b.ToTable("Usuarios", (string)null);
                });

            modelBuilder.Entity("ProyTelesecundaria.Models.AlumnoMateria", b =>
                {
                    b.HasOne("ProyTelesecundaria.Models.Materia", "Materia")
                        .WithMany("AlumnoMaterias")
                        .HasForeignKey("IDMateria")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("ProyTelesecundaria.Models.Alumnos", "Alumno")
                        .WithMany("AlumnoMaterias")
                        .HasForeignKey("Matricula")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Alumno");

                    b.Navigation("Materia");
                });

            modelBuilder.Entity("ProyTelesecundaria.Models.MaestroMateria", b =>
                {
                    b.HasOne("ProyTelesecundaria.Models.Maestros", "Maestro")
                        .WithMany("MaestroMaterias")
                        .HasForeignKey("IDMaestro")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("ProyTelesecundaria.Models.Materia", "Materia")
                        .WithMany("MaestroMaterias")
                        .HasForeignKey("IDMateria")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Maestro");

                    b.Navigation("Materia");
                });

            modelBuilder.Entity("ProyTelesecundaria.Models.Maestros", b =>
                {
                    b.HasOne("ProyTelesecundaria.Models.Aula", "Aula")
                        .WithMany()
                        .HasForeignKey("IdAula")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Aula");
                });

            modelBuilder.Entity("ProyTelesecundaria.Models.Alumnos", b =>
                {
                    b.Navigation("AlumnoMaterias");
                });

            modelBuilder.Entity("ProyTelesecundaria.Models.Maestros", b =>
                {
                    b.Navigation("MaestroMaterias");
                });

            modelBuilder.Entity("ProyTelesecundaria.Models.Materia", b =>
                {
                    b.Navigation("AlumnoMaterias");

                    b.Navigation("MaestroMaterias");
                });
#pragma warning restore 612, 618
        }
    }
}
